### ISSUE TITLE
Matrix Field not possible to import

### ISSUE THREAD

**Issue by sidneywidmer** [engram-design/FieldManager#26]
It's currently not possible to export and import a matrix field. Unfortunately I have no idea where the error is. 

Steps to reproduce this issue:
1. Set up fresh craft installation
2. Install latest FieldManager Plugin
3. Try to import the following json:
````
{
    "foo": {
        "name": "foo",
        "context": "global",
        "instructions": "",
        "translatable": 0,
        "type": "Matrix",
        "settings": {
            "maxBlocks": null
        },
        "blockTypes": {
            "bar": {
                "name": "bar",
                "fields": {
                    "bat": {
                        "name": "bat",
                        "required": 1,
                        "instructions": "",
                        "translatable": 0,
                        "type": "PlainText",
                        "settings": {
                            "placeholder": "",
                            "maxLength": "",
                            "multiline": "",
                            "initialRows": 4
                        }
                    }
                }
            }
        }
    }
}
````

It won't throw an error or anything and the field is also created in the craft backend. There is also a table created called `craft_matrixcontent_foo` but the essential column `field_bar_bat` is missing in this table. So if you ad the field to the field layout of an entry or similar, it will throw an error as soon as you try to edit/create. If you go to the cp settings page, open the foo field and save it craft automatically fixes the problem by adding the missing column. 

Is this a local issue or can anyone reproduce this to verify?

**Comment by engram-design** [comment]
This is now fixed in version [1.5.0](https://github.com/engram-design/FieldManager/releases/tag/1.5.0).

**Comment by brandondeweese** [comment]
This still doesn't work. I can't import any fields contained within a matrix.. ...Am I missing something?

PHP version	7.3.5
OS version	Darwin 19.6.0
Database driver & version	MySQL 8.0.16
Image driver & version	GD 7.3.5
Craft edition & version	Craft Pro 3.5.11.1
Yii version	2.0.38
Twig version	2.12.5
Guzzle version	6.5.5
Imagine version	1.2.3-dev
Field Manager | 2.2.1

**Comment by engram-design** [comment]
@brandondeweese Note that the above is for Craft 2, so if you're trying to use that you'll get errors.

For instance, the above can be translated to Craft 3 using the following format:

```
[
    {
        "name": "foo",
        "handle": "foo",
        "instructions": "",
        "required": null,
        "searchable": 0,
        "translationMethod": "site",
        "translationKeyFormat": null,
        "type": "craft\\fields\\Matrix",
        "settings": {
            "minBlocks": "",
            "maxBlocks": "",
            "propagationMethod": "all",
            "blockTypes": {
                "new1": {
                    "name": "Bar",
                    "handle": "bar",
                    "fields": {
                        "new1": {
                            "name": "Bat",
                            "handle": "bat",
                            "required": 0,
                            "instructions": "",
                            "searchable": 0,
                            "translationMethod": "none",
                            "translationKeyFormat": null,
                            "type": "craft\\fields\\PlainText",
                            "typesettings": {
                                "uiMode": "normal",
                                "placeholder": "",
                                "code": "",
                                "multiline": "",
                                "initialRows": 4,
                                "charLimit": null,
                                "byteLimit": null,
                                "columnType": null
                            },
                            "width": 50
                        }
                    }
                }
            }
        }
    }
]
```

Which I've just imported without issue (note all those settings aren't strictly required). Are you receiving any errors, or is the field importing, but missing inner fields?
